server:
  port: 8081
spring:
  dubbo:
    application:
      name: order-web
    registry:
      protocol: zookeeper
      address: ${DUBBO_ADDRESS:192.168.1.101:2181}
    base-package: com.luka.gmall
    protocol:
      name: dubbo
    consumer:
      timeout: ${DUBBO_TIMEOUT:10000}
      check: false